Implement a custom get-go-imports command t
nx-go/nx-go pull request #84
Opened 2023-02-02 18:07 UTC by meDavidNS

This PR updates the go-package-graph to use a Go AST lookup for the imports. The reduces the required time for a full graph calculation on our repository for 6-7 minutes to a few seconds

2023-02-04 12:49 UTC, phillipCouto requested changes
Great contribution @meDavidNS! There are just a few things to clean up and then this is definitely ready to be merged!

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +	if len(os.Args) == 1 {
**suggestion:** Change this to `if len(os.Args) != 2 {`.

This way we can throw an error if too many arguments are provided as well. We can then update the error message to:

> path to a directory is required, only one argument can be provided.

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +type FileImportsInfo struct {
**cleanup:** Looks like this is no longer used.

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +	}
**suggestion:** Expand the error handling to account for other types of errors.

```go
if err != nil && !os.IsNotExist(err)  {
  println("error accessing path",dirPath,": ", err)
  return
} else if err != nil  || !info.IsDir(){
  println("could not find directory:", dirPath)
  return
}
```

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +		println("bail out, error reading dir")
**issue:** The error should be returned so it can help with diagnosing the issue.

```go
println("error reading dir: ". err)
```

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +	//var fileImportsInfo []FileImportsInfo
**cleanup:** Clean up commented out code.

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +		//fileImportsInfo = append(
**cleanup:** Cleanup commented out code.

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +		return nil, errors.New("error reading dir")
**suggestion:** Wrap the error so the calling code can see what is causing a problem.

```go
return nil, fmt.Errorf("error reading '%v': %w", path, err)
```

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +	var goImports = make([]string, 0)
**suggestion:** Simplify by changing to `var goImports []string`

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/get-go-imports.go
> +package main
**issue:** We are missing a `go.mod` file to track the dependencies of the code.

Please add a `go.mod` file in the `packages/nx-go` folder.

We need to then add `"packages/nx-go/go.mod",` to https://github.com/nx-go/nx-go/blob/main/packages/nx-go/project.json#L29

2023-02-04 12:49 UTC, phillipCouto commented on packages/nx-go/src/go-package-graph/index.ts
> +  const fileImportsMap = JSON.parse(fileImportsInfoJsonStr)
**suggestion:** Create a type defining the expected structure so typescript can help with type checking.

```ts
// Add at the bottom of the file
interface GoCodeImports {
 [key: string]: string[]
}
...

const fileImportsMap = JSON.parse(fileImportsInfoJsonStr) as GoCodeImports
```

Also rename `fileImportsMap` to something a little more descriptive, maybe `goFileImportMap`?

2023-09-13 20:34 UTC, meDavidNS commented
Sorry about that. I'll see if I get reserve some time next week. By all means improve upon my initial work

2023-09-15 18:05 UTC, phillipCouto commented
> Sorry about that. I'll see if I get reserve some time next week. By all means improve upon my initial work

Not a problem 🙂, life happens. I just wanted to make sure you were still interested in implementing the change.

I will wait for you to work on the issue. If you don't have time and would rather we finish the implementation just let us know.

2024-02-22 19:01 UTC, utarwyn commented
Hello!

Thank you for this great work on a rather important issue in version 2 of the plugin. I suggested another approach in #103 (for  nx-go v3) that will directly read Go file imports without any additional program.

I've done a few tests on large projects, and got a significant improvement in graph performance. This feature is enabled by default from version 3, as I consider it to be an important addition to Nx that should not be optional. I've just released version 3.0.0-beta.0 if you'd like to try it out. So if you have any further feedback on this subject, I'd be delighted to hear from you, in #107.

Thanks again! 🤝

2024-02-22 19:01 UTC, closed without merging